### ISSUE TITLE
Flag that access to Azure KeyVault is disabled

### ISSUE THREAD

**Issue by souzagustavo** [srempfer/spring-cloud-config-azure-keyvault#164]
Hi,

I'm trying to use the `enable` flag to disable key vault integration momentarily, but it has no effect.

The Secrets are still listed

![image](https://github.com/srempfer/spring-cloud-config-sample/assets/35812662/9cf8a4b4-a01b-46c7-9323-0acc279df3e2)

application.yaml
```
spring:   
  cloud:
    config:
      server:
        azure:
          keyvault:
            uri: ${KEYVAULT_URI}
            client-id: ${KEYVAULT_CLIENT_ID}
            client-key: ${KEYVAULT_CLIENT_SECRET}
            tenant-id:  ${AZ_TENANT_ID}
            enabled: false
        git:
          refreshRate: 30
          clone-on-start: true
          uri: ${GIT_URI}
```

build.gradle
```
plugins {
  id 'org.springframework.boot' version '2.3.5.RELEASE'
  id 'io.spring.dependency-management' version '1.0.10.RELEASE'
  id 'java'
}

group = 'com.superdigital'
version = '0.0.2-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
  mavenCentral()
}
ext {
  set('springCloudVersion', "Hoxton.SR8")
}

configurations {
    compile.exclude module: 'tomcat-embed-core'
    compile.exclude module: 'spring-boot-starter-tomcat'
    compile.exclude group: 'tomcat-embed-el'
}

dependencies {
	implementation 'org.springframework.cloud:spring-cloud-config-server'
	implementation 'org.springframework.boot:spring-boot-starter-undertow'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
        implementation 'io.github.srempfer:spring-cloud-config-azure-keyvault-starter:0.5.0'
}

dependencyManagement {
  imports {
    mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
  }
}
```

Am I using it correctly?

Also check that method [getEnabled ()](https://github.com/srempfer/spring-cloud-config-azure-keyvault/blob/dde91162d81a665c34337553a746868208ec8df6/spring-cloud-config-azure-keyvault-starter/src/main/java/org/srempfer/cloud/config/keyvault/autoconfigure/KeyVaultProperties.java#L72) has no references.
